In [145]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [146]:
from sklearn.datasets import load_digits
digits = load_digits(as_frame=True)
df = digits.frame

In [147]:
df.head()

,pixel_0_0,pixel_0_1,pixel_0_2,pixel_0_3,pixel_0_4,pixel_0_5,pixel_0_6,pixel_0_7,pixel_1_0,pixel_1_1,...,pixel_6_7,pixel_7_0,pixel_7_1,pixel_7_2,pixel_7_3,pixel_7_4,pixel_7_5,pixel_7_6,pixel_7_7,target
0,0.0,0.0,5.0,13.0,9.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,6.0,13.0,10.0,0.0,0.0,0.0,0
1,0.0,0.0,0.0,12.0,13.0,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,11.0,16.0,10.0,0.0,0.0,1
2,0.0,0.0,0.0,4.0,15.0,12.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,3.0,11.0,16.0,9.0,0.0,2
3,0.0,0.0,7.0,15.0,13.0,1.0,0.0,0.0,0.0,8.0,...,0.0,0.0,0.0,7.0,13.0,13.0,9.0,0.0,0.0,3
4,0.0,0.0,0.0,1.0,11.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,2.0,16.0,4.0,0.0,0.0,4

In [148]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:-1],df.iloc[:,-1],test_size=0.2,random_state=2)

In [149]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [150]:
clf1 = LogisticRegression()
clf2 = DecisionTreeClassifier(max_depth=None,criterion='entropy')

In [151]:
clf1.fit(X_train,y_train)
clf2.fit(X_train,y_train)

c:\Users\ossal\Documents\pythonProject\py_proj\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

DecisionTreeClassifier(criterion='entropy')

In [152]:
y_pred1 = clf1.predict(X_test)
y_pred2 = clf2.predict(X_test)

In [153]:
from sklearn.metrics import accuracy_score,confusion_matrix
print("Accuracy of Logistic Regression",accuracy_score(y_test,y_pred1))
print("Accuracy of Decision Trees",accuracy_score(y_test,y_pred2))

Accuracy of Logistic Regression 0.9444444444444444
Accuracy of Decision Trees 0.85

In [154]:
print("Logistic Regression Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,10)))

Logistic Regression Confusion Matrix

    0   1   2   3   4   5   6   7   8   9
0  31   0   0   0   1   0   0   0   0   0
1   0  41   0   1   0   0   0   0   1   1
2   0   0  31   0   0   0   0   0   0   0
3   0   0   0  33   0   0   0   1   2   0
4   0   0   0   0  31   0   0   0   3   1
5   0   1   0   0   1  41   0   0   0   0
6   0   1   0   0   0   0  33   0   1   0
7   0   0   0   0   0   0   0  39   0   1
8   0   0   0   0   0   0   0   0  35   1
9   0   0   0   1   0   1   0   0   1  25

In [155]:
print("Decision Tree Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred2),columns=list(range(0,10)))

Decision Tree Confusion Matrix

    0   1   2   3   4   5   6   7   8   9
0  30   0   0   0   0   0   0   0   2   0
1   0  35   2   4   0   1   1   1   0   0
2   0   1  27   1   0   0   0   0   2   0
3   0   1   0  30   0   0   0   1   4   0
4   0   1   0   0  27   0   0   3   3   1
5   0   1   0   0   2  37   0   0   0   3
6   0   0   1   0   0   1  31   0   1   1
7   0   1   0   0   0   0   0  38   1   0
8   0   1   4   2   0   0   0   0  25   4
9   0   0   0   0   0   0   0   1   1  26

In [156]:
from sklearn.metrics import precision_score,recall_score,f1_score

In [157]:
precision_score(y_test,y_pred1,average='weighted')

0.9477543902383517

In [158]:
recall_score(y_test,y_pred1,average='weighted')

0.9444444444444444

In [159]:
f1_score(y_test,y_pred1,average='weighted')

0.9451471115572613

In [160]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred1))

              precision    recall  f1-score   support

           0       1.00      0.97      0.98        32
           1       0.95      0.93      0.94        44
           2       1.00      1.00      1.00        31
           3       0.94      0.92      0.93        36
           4       0.94      0.89      0.91        35
           5       0.98      0.95      0.96        43
           6       1.00      0.94      0.97        35
           7       0.97      0.97      0.97        40
           8       0.81      0.97      0.89        36
           9       0.86      0.89      0.88        28

    accuracy                           0.94       360
   macro avg       0.95      0.94      0.94       360
weighted avg       0.95      0.94      0.95       360